version: '3.9'
services:
  nginx:
    container_name: event_calendar_nginx
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html

  app:
    container_name: event_calendar_app
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/php/php.ini
      - ./:/var/www/html
    ports:
      - "5173:5173"

  db:
    container_name: event_calendar_db
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - event_calendar_db_volumes:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=event_calendar_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  phpmyadmin:
    container_name: event_calendar_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_ROOT_PASSWORD=root

volumes:
  event_calendar_db_volumes: